# The protocol to be used in request url, defaults to https
@protocol = http://

# The domain of the server, example: example.com
@domain = 18.194.113.79

# The FQDN of the server, example: https://example.com
@baseUrl = {{protocol}}{{domain}}

# The path of the resource
@path = records

##### Valid Request #####
### The HTTP request to fetches records for the following criteria:
### 1. the `createdAt` field of a document is in between `startDate` and `endDate`
### 2. the sum of the `counts` field of a document is between `minCount` and `maxCount`
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "startDate": "2016-01-26",
      "endDate": "2018-02-02",
      "minCount": 2700,
      "maxCount": 3000
}

##### Invalid Request 1 #####
### minCount is missing
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "startDate": "2016-01-26",
      "endDate": "2018-02-02",
      "maxCount": 3000
}

##### Invalid Request 2 #####
### maxCount is missing
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "startDate": "2016-01-26",
      "endDate": "2018-02-02",
      "maxCount": 3000
}

##### Invalid Request 3 #####
### startDate is missing
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "endDate": "2018-02-02",
      "minCount": 2700,
      "maxCount": 3000
}

##### Invalid Request 4 #####
### endDate is missing
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "startDate": "2016-01-26",
      "minCount": 2700,
      "maxCount": 3000
}

##### Invalid Request 5 #####
### startDate is not properly formatted
POST {{baseUrl}}/{{path}} HTTP/1.1
Content-Type: application/json

{
      "startDate": "2016.01.26",
      "endDate": "2018-02-02",
      "minCount": 2700,
      "maxCount": 3000
}